#ONLY FOR DEV : this docker-compose is overrided in production mode
version: '3.7'
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: portfolio-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - './:/var/www'
    networks:
      - travellist
  db:
    image: postgres:latest
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_PASSWORD: '00000000'
      POSTGRES_USER: postgres
      POSTGRES_DB: 'portfolio'
    ports:
      - '5432:5432'
    networks:
      - travellist
    volumes:
      - dbdata:/var/lib/postgresql/data

  nginx:
    image: 'nginx:alpine'
    container_name: portfolio-nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - './:/var/www'
      - './docker-compose/nginx:/etc/nginx/conf.d'
    networks:
      - travellist

  redis:
    image: "redis:alpine"
    container_name: portfolio-redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - travellist
    volumes:
      - redis:/data

networks:
  travellist:
    driver: bridge
volumes:
  dbdata:
  redis:
